### PR TITLE
Make the controller value out of range to not fail

### PR DESCRIPTION
**Pull request by Wohlstand**
This should fix the inability to open some MIDI files like this one: [Witchy_3.mid.zip](https://github.com/adambiser/imf-creator/files/6083831/Witchy_3.mid.zip)

### CODE REVIEW

**Comment by adambiser** [comment]
The controller change value is read with _u8, so it should never be < 0.  Rather than clamping, it would probably be better to do a bitwise and with 0x7f.  This is what Cakewalk does with those volume controller values: 0xfe becomes 126.

What program did you use to create these files?  What volumes does it show for those channels ("Trombon", "Strings")?

**Comment by Wohlstand** [comment]
> What program did you use to create these files?

I took the file that made not by me:
[Witchy.mid.zip](https://github.com/adambiser/imf-creator/files/6093318/Witchy.mid.zip)

Then, I edited it in Sekaiju MIDI editor, I made the remake from it, and it's this:
[Witchy_3.mid.zip](https://github.com/adambiser/imf-creator/files/6093322/Witchy_3.mid.zip)

Sekaiju doesn't change such odd values and keeps them in as-is form, however, it can fix other defects in MIDI files and it notices about them. About the `< 0`, I'll quickly fix this.

**Comment by Wohlstand** [comment]
>  What volumes does it show for those channels ("Trombon", "Strings")?

Lemme check that...

**Comment by Wohlstand** [comment]
Снимок экрана от 2021-03-05 23-57-42

At the track, it shows that volume is undefined, at raw MIDI events editor, it shows that the first volume event has the `254` value, it's invalid. If I try to change it, Editor automatically fixes it into the valid range and doesn't allow me to fill the invalid value. However, for existing MIDI files it doesn't correcting such values.

**Comment by Wohlstand** [comment]
If I filter volume controllers, I'll see that some of the volume events have invalid values here. The original file (from what I made the remake) was taken from the wild, and it has these invalid values.
Снимок экрана от 2021-03-05 23-59-58

**Comment by adambiser** [comment]
Interesting.  I'd prefer to go with how Cakewalk interprets the value:
`value &= 0x7f`
rather than
`value = 127`
The controller change value should only be 7 bits.  The 8th bit should just be ignored.

**Comment by Wohlstand** [comment]
Okay, will do

**Comment by Wohlstand** [comment]
Done

**Comment by adambiser** [comment]
Thanks

**Pull request merged**
