### PR TITLE
Fixed distortion caused by incorrect volume formula

### PR DESCRIPTION
**Pull request by Wohlstand**
Because of incorrect volume formula, generated IMF files aren't sounded good. I have fixed that:
- When voice is FM, scale carrier only
- When voice is AM, scale both operators
- KSL didn't aligned right, I have added the shift that fixes it

### CODE REVIEW

**Comment by adambiser** [comment]
Are you able to do a few things before I pull this?
1) Split the console code and IMF-1 size overflow fix into their own individual pull requests?
1) Provide an example MIDI, an IMF with the distortion (pre-fix conversion) and one with how it sounds with the fix code?

Thanks.

**Comment by Wohlstand** [comment]
1. For that, I will need to make a separate branch... But it's possible.
2. Yeah, that a quick, wait few minutes... :fox_face: :wink:

**Comment by adambiser** [comment]
Don't worry about splitting them if it'll be too much trouble.  The MIDI + IMFs would be most useful.

I hadn't gotten around to developing the console interface, but something that makes it easier to use is good.  I had planning on an UI eventually.

Thanks.

**Comment by Wohlstand** [comment]
[imf-before-and-after-distortion-fix.zip](https://github.com/adambiser/imf-creator/files/3315394/imf-before-and-after-distortion-fix.zip)
Made!
I have made IMF-1 files and for convenience of listening, I have recorded OGGs.
I also have included my bank I have used. To verify the sounding, I have my own things you can use:
* [OPL3 Bank Editor](https://github.com/Wohlstand/OPL3BankEditor) which allows edit and create OPL3 FM banks of various formats. (Fresh builds you can find here https://github.com/Wohlstand/OPL3BankEditor#download)
* [libADLMIDI](https://github.com/Wohlstand/libADLMIDI) - a library and console MIDI player that is able to play MIDI files on emulated OPL3 chips and also is able to play IMF-1 files. (you can find ready-for-use software you can use without building of library by yourself: https://github.com/Wohlstand/libADLMIDI#working-demos)

**Comment by Wohlstand** [comment]
Another samples:
* [d_c1m1-mid-to-imf.zip](https://github.com/adambiser/imf-creator/files/3315461/d_c1m1-mid-to-imf.zip)
* [d_c2m8.zip](https://github.com/adambiser/imf-creator/files/3315466/d_c2m8.zip)
* [3D Lemmings - 03 - Army 1.zip](https://github.com/adambiser/imf-creator/files/3315481/3D.Lemmings.-.03.-.Army.1.zip)
* [DemoWave.zip](https://github.com/adambiser/imf-creator/files/3315523/DemoWave.zip)

**Comment by Wohlstand** [comment]
> I had planning on an UI eventually.

Both console and UI are good: the UI for regular users and console for the ability to use it with scripts or as a backend for something.

**Comment by adambiser** [comment]
Where can I hear the distortion best in your examples?  I mainly hear a drop in volume.
ie: The guitar part at 1:17 in d_c2m8 almost disappears in d_c2m8.mid.imf but can be heard in d_c2m8 - before.imf.

**Comment by Wohlstand** [comment]
> Where can I hear the distortion best in your examples? I mainly hear a drop in volume.
> ie: The guitar part at 1:17 in d_c2m8 almost disappears in d_c2m8.mid.imf but can be heard in d_c2m8 - before.imf.

Pay attention to sounding of drums and distortion guitar. Before the fix, snare drums are sounding totally incorrectly.
However, you can compare the sounding with this tool: http://wohlsoft.ru/docs/_laboratory/_Builds/win32/bin-w64/_packed/pge-musplay-dev-win64.zip
* open it
* open "Setup -> MIDI Settings"
* In the "ADLMIDI Extra setup", in the "ADLMIDI bank id" choose the "74 WOPL (Apogee IMF 90-ish)"
* Drop any MIDI file into the main window
* You'll hear the sounding which is valid.

The backend which will play this MIDI file is my libADLMIDI project: https://github.com/Wohlstand/libADLMIDI

**Comment by Wohlstand** [comment]
As an addition, I'll explain your mistakes in the formula: when you applied a volume level to voice, you have missed up the difference of FM and AM voices: when you modify the volume of the modulator of FM voice, you'll change the brightness, not the volume. Don't change a volume of both operators when voice is FM. So, modify carrier only to change the volume of FM sound without distortion. FM voice is a result of a carrier passed through a modulator. When it's AM voice, both operators playing as independent simple waves are summed between each other. In this case, you need to modify a volume of both operators. Otherwise, if you will don't modify a volume of the second operator, you'll still hear a sound.

Your mistake is that you have used AM logic to absolutely any voices. FM voices need a different logic I have implemented. You'll see that for FM voice I only passing the volume of modulator as-is while scaling the carrier operator.

**Comment by Wohlstand** [comment]
P.S. If you want to experiment with different banks, feel free to use my OPL3-BE which has support for a lot of formats include DMX OP2: https://github.com/Wohlstand/OPL3BankEditor, and you are able to convert banks from other formats. (downlad you'll find inside ReadMe)

**Comment by adambiser** [comment]
I've been reading AM in this commit and thinking Amplitude Modulation, which also modulates a carrier wave, rather than Additive Synthesis.  It has been awhile since I've worked on this project, obviously, and took a minute to get into the correct mindset.

What you've done looks correct.
I wonder whether get_operator_volume is correct.  I'll have to take a look at that sometime.

**Pull request merged**
