### PR TITLE
Fixed processing of some MIDI files

### PR DESCRIPTION
**Pull request by Wohlstand**
Example files are won't work without of my fix:
[drunken_sailor_minimized.mid.zip](https://github.com/adambiser/imf-creator/files/3823768/drunken_sailor_minimized.mid.zip)
[russian_r'n'b_ish_folk.mid.zip](https://github.com/adambiser/imf-creator/files/3823769/russian_r.n.b_ish_folk.mid.zip)

### CODE REVIEW

**Comment by adambiser** [comment]
Thanks for pointing out these problems.

The freq going too high was caused by a miscalculation in the pitch bend down code:  it was subtracting a negative semitone and going upward instead.  Another bug in the freq adjustment at the end of that code block compensated in my test cases but failed in yours.  Fixing these two bugs eliminates the "freq too high" problem with russian_r'n'b_ish_folk.mid without the need of your additions.  It already does the block multiplying that you mention in the comments.

I'm going to add drum mapping for the GM level 2 drums and only silence those that don't map.  The current code has too-low drum notes become upper value melodic instruments and this pull request doesn't fix that, just too-high drum notes.

Again, thanks for pointing out both of these bugs.

**Comment by Wohlstand** [comment]
>  It already does the block multiplying that you mention in the comments.

In my comment I meant another: when the block has reached a maximum and both block and frequency are at maximum. So, after this edge point, it needs to increase the frequency multiplier value of every operator to allow these notes sound higher. This often happens on some MIDI drivers and instruments, and one of the examples is DMX: if you trying to play sound higher than 7'th octave, all notes will use the same edge note together. Inside of libADLMIDI, I have resolved this problem and notes in DMX banks are now able to sound higher than this edge.

Anyway, thanks for more detailed analysis, yeah, I am ready to check the case more deeply. This PR I have sent is some sort of a quick fix (which is not in real). Good that you have pointed it's problems and helped to find a true reason for it. I didn't research this completely yet because I was at my job and I wanted to fix it quickly. The reason why I tried to make these fixes because there are several files are caused by a crash of the program with error in these places.

> I'm going to add drum mapping for the GM level 2 drums and only silence those that don't map. The current code has too-low drum notes become upper-value melodic instruments and this pull request doesn't fix that, just too-high drum notes.

The mapping is should be here, yeah. I think, the array of instruments should be replaced with a `dict()` for a better mapping :thinking: (so, give a silence when no instruments found here).
P.S. The reason why they are too high they are going out of the GM range (80 drum instruments) and the OP2 set doesn't contain necessary instruments. I going to change this to guarantee 128:128 for GM and (as a small bonus and addition) I going to add the support for WOPL bank format which is more flexible than DMX's OP2.

**Comment by adambiser** [comment]
I understand what you mean now about utilizing the frequency multiplier to go higher.  I'll take a look at what libADLMIDI does sometime.

As for drum mapping, I only used the DMX format because I was familiar with it from Doom and had also used it in the VB6 version of IMFCreator.  I'll take a look at your WOPL code sometime soon-ish.

**Comment by Wohlstand** [comment]
Yeah, I knew this format for a long time, and while I was a child, I have used your VB6-coded IMF Creator for it's bank editor to make custom OP2 files to mod DOOM 🦊
Anyway, later I coded my own bank editor (OPL3 Bank Ediror) which now supports this format, and also supports lots of others! 🦊
So, feel free to try it out and if you want, you can suggest it here in readme for users who want make a custom OP2 bank files.

**Comment by adambiser** [comment]
I'll definitely look into it.  I originally planned on this project to be a 1-to-1 conversion of the VB6 program without really looking into what new things could be implemented, but development came to a standstill.

**Pull request closed without merging**
