### PR TITLE
A bunch of works made in a week

### PR DESCRIPTION
**Pull request by Wohlstand**
- Reworked "instruments" array, now it's a tree with `"m/p"->bankId->instrumentId` branches
- Implemented support of WOPL bank files (rhythm-mode drums and 4op instruments are dropping as unsupported)
- Improvement of GUI: added two buttons to load bank and song on the fly, added menubar with some menu items working
- Added pitch bend sensitivity change support (I made the handling of NRPN/RPN parsing to support that)
- Added using of bank change code that will be useful with WOPL files
- Added "CC11" support as an alternative volume change factor
- Added "CC74" support which allows to affect modulator and use it for extra expressioning (Two little examples with CC74: [Ecu_10_Bass_xg-hr.zip](https://github.com/adambiser/imf-creator/files/3851326/Ecu_10_Bass_xg-hr.zip), [You_39_re_Back.zip](https://github.com/adambiser/imf-creator/files/3852219/You_39_re_Back.zip))

### CODE REVIEW

**Comment by adambiser** [comment]
I'm going to be updating this project to Python 3 as well as solidifying plugin and instrument management, which would likely cause this code to not work.  Once I've updated, I'll take a look into porting this pull request to work with the changes.

**Comment by Wohlstand** [comment]
I don't think it's a good idea to do this work before merging which will introduce lots of extra unnecessary works. Porting into Python 3 together with applying a syntax and library names changes, also requires to port the PyOPL3 thing which is strictly assigned with a Python2 right now.

**Comment by adambiser** [comment]
I've modified the PyOPL code to compile both Python 2 and 3 versions, so that won't be an issue.  I just need to commit it when I get the chance.

**Comment by adambiser** [comment]
I've forked PyOPL and made the changes to it at https://github.com/adambiser/pyopl
The code should compile and work for both Python 2 and 3.  I've tried the demo script in 2.7 and 3.7 for Windows.

**Comment by adambiser** [comment]
When you get the chance, would you try out the python3 branch?  You'll need to compile https://github.com/adambiser/pyopl for Python 3 support on Linux.  I believe I've implemented all of the changes you've made in the pull request.

The way "filetypes" and "filetype settings" are declared for each plugin type might change in the near future.

I've tried to make it more flexible so that additional file types can be converted from/to.  For instance, this code can convert Doom's MUS files to IMF as well.

**Comment by Wohlstand** [comment]
Oh, cool!
Yeah, I'll try to compile it once I'll reach a computer, right now I'm in a path to my workplace, will be at work approximately after 1.5 hours.

**Comment by Wohlstand** [comment]
Okay, I have took the thing, and it works. I wondered why main.py ran an old clunky eye-like test thing, however, I figured out that I need to run `python3 -m imfcreator` to start the normal utiltiy itself :thinking: 
I have found one bug which prevented app to be ran: you tried to import a thing that wasn't initialized before. So, I have fixed this by calling plugins loading externally, after the moment when all modules was been initialized. I have updated the documentation to mention that thing will work with Python 3.5 fine, and I have built the PyOPL for Linux x86_64 platform that works at me.

So, I sent my patch for that here: https://github.com/adambiser/imf-creator/pull/7

**Comment by adambiser** [comment]
Correct, I did change it so that the module needs to be run.  I should have mentioned that.

**Comment by adambiser** [comment]
Aside from PR #7 , does the python3 branch have everything this pull request had?
If so, I'll close it.

**Comment by Wohlstand** [comment]
I think, should be fine now. 
You would merge my patch with this (make the new "python2" branch for historical purposes), and then merge "python3" into "master" as I see it should be ready now. All future works can be made as "master".

> make the new "python2" branch for historical purposes

I mean, if anything will be missed up, we still can check out this old patch to find any hints.

**Comment by adambiser** [comment]
I agree with creating a python2 branch.  Will do this later.

**Comment by Wohlstand** [comment]
Hello! I think, it's time to turn the "python3" branch into master. :fox_face:  I see you created the "python2" branch, but still didn't update master with python3's content :eyes:  Do you have some planned works before to make that?

**Comment by adambiser** [comment]
Yep, working on it.  See a few things to change first though.

**Pull request closed without merging**
